### ISSUE TITLE
test for blog

### ISSUE THREAD

**Issue by harsh-9in** [harsh-9in/Blogger#156]
**Is your feature request related to a problem? Please describe.**
In the test.py file of the blog model, we want to add tests.

**Comment by shraddhavp** [comment]
interested sir

**Comment by harsh-9in** [comment]
Assigned to @shraddhavp

**Comment by shraddhavp** [comment]
@harsh-9in  sir can you please let me know some example test cases needed?

**Comment by harsh-9in** [comment]
Do you need documentation or resources?

**Comment by shraddhavp** [comment]
documentation sir

**Comment by harsh-9in** [comment]
https://docs.djangoproject.com/en/3.1/topics/testing/overview/

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Testing

https://www.youtube.com/watch?v=DmRpNoQEx2o

https://www.youtube.com/watch?v=0MrgsYswT1c

https://www.youtube.com/watch?v=WWa4bzTJZgI

**Comment by harsh-9in** [comment]
Hope this help and If you still have trouble feel free to discuss in the channel.

**Comment by shraddhavp** [comment]
yes sure I will look into the links thank you

**Comment by harsh-9in** [comment]
@shraddhavp are you still working on this issue?

**Comment by shraddhavp** [comment]
yes sir @harsh-9in

**Comment by harsh-9in** [comment]
okk @shraddhavp :+1:

**Comment by chetak123** [comment]
can i work on this issue please ?

**Comment by harsh-9in** [comment]
assigned to you @chetak123

**Comment by chetak123** [comment]
sir i have installed requirement.txt
but when i try to do makemigration its showing this error
➜  mysite git:(master)$  python3 manage.py makemigrations                                   
Traceback (most recent call last):
  File "/home/chetak/Documents/Dev/github/dwoc/bloger/Blogger/mysite/manage.py", line 21, in <module>
    main()
  File "/home/chetak/Documents/Dev/github/dwoc/bloger/Blogger/mysite/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/chetak/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/chetak/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/home/chetak/.local/lib/python3.9/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/chetak/.local/lib/python3.9/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/chetak/.local/lib/python3.9/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/chetak/Documents/Dev/github/dwoc/bloger/Blogger/mysite/mysite/settings.py", line 24, in <module>
    SECRET_KEY = config('SECRET_KEY')
  File "/home/chetak/.local/lib/python3.9/site-packages/decouple.py", line 199, in __call__
    return self.config(*args, **kwargs)
  File "/home/chetak/.local/lib/python3.9/site-packages/decouple.py", line 83, in __call__
    return self.get(*args, **kwargs)
  File "/home/chetak/.local/lib/python3.9/site-packages/decouple.py", line 68, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.

If you suspect this is an IPython 7.17.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

(my system information is Linux parrot 5.7.0-2parrot2-amd64 #1 SMP Debian 5.7.10-1parrot2 (2020-07-31) x86_64 GNU/Linux)

**Comment by chetak123** [comment]
sir i have installed requirement.txt file , changed the secret-key to .env . But i am not able to access home page (127.0.0.1:8000)

the error shown is as follows:
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/

Django Version: 3.0.8
Python Version: 3.8.5
Installed Applications:
['blog.apps.BlogConfig',
 'django.contrib.admin',
 'crispy_forms',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'users.apps.UsersConfig',
 'ckeditor',
 'ckeditor_uploader',
 'taggit',
 'rest_framework']
Installed Middleware:
('whitenoise.middleware.WhiteNoiseMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')



Traceback (most recent call last):
  File "/home/ayush/Documents/github/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ayush/Documents/github/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ayush/Documents/github/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ayush/Documents/github/env/Blogger/mysite/blog/views.py", line 41, in home
    mostliked1 = Post.objects.get(id=1)
  File "/home/ayush/Documents/github/env/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ayush/Documents/github/env/lib/python3.8/site-packages/django/db/models/query.py", line 415, in get
    raise self.model.DoesNotExist(

Exception Type: DoesNotExist at /
Exception Value: Post matching query does not exist.

(my system information is Linux ayushman 5.4.0-48-generic 52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux)

**Comment by harsh-9in** [comment]
You have to create a minimum of four blogs. You may create a superuser and then from admin panel create 4 blogs then you will be able to access.
